//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewGenGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamesInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GamesInfo()
        {
            this.Videos = new HashSet<Video>();
        }
    
        public int GameID { get; set; }
        public int LangID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Lang Lang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Video> Videos { get; set; }
    }
}
